export const reviewArr = [
    {
        id:0,
        idApt:0,
        nameUser:"klx",
        idUser:0,
        idTypeRoom:1,
        score:5,
        detail:"ดีมากเลย"
    },
    {
        id:1,
        idApt:0,
        nameUser:"Noctice",
        idUser:0,
        idTypeRoom:1,
        score:5,
        detail:""
    },
    {
        id:2,
        idApt:1,
        nameUser:"A",
        idUser:1,
        idTypeRoom:2,
        score:5,
        detail:"ดีมากเลย"
    },
    {
        id:3,
        idApt:1,
        idTypeRoom:0,
        idUser:2,
        nameUser:"B",
        score:3,
        detail:"กลางๆ"
    },
    {
        id:4,
        idApt:1,
        idTypeRoom:0,
        idUser:3,
        nameUser:"C",
        score:3,
        detail:"กลางๆ"
    },
    {
        id:5,
        idApt:1,
        idTypeRoom:0,
        idUser:4,
        nameUser:"D",
        score:3,
        detail:"กลางๆ"
    }
]
    
